#This is a CREST input file
#A customized input for conformational sampling. All metadynamics calculations will be #run at GFN-FF level, but optimizations are run at GFN2-xTB level. Furthermore, #multilevel optimization is turned off (expensive).
#https://crest-lab.github.io/crest-docs/page/documentation/inputfiles_examples.html#conformational-sampling-custom
input='struc.xyz'
runtype='imtd-gc'
multilevelopt=false

#parallelization
threads=8

#calculation data
[calculation]
[[calculation.level]]
method="gfnff"
weight=1.0

[[calculation.level]]
method='gfn2'

#molecular dynamics data (activate only GFN-FF)
[dynamics]
active=[1]
